### ISSUE TITLE
No reconnect after an internet offline issue

### ISSUE THREAD

**Issue by AleksCee** [philipparndt/miele-to-mqtt-gw#40]
Hi,

today my internet was down for 2 1/2h and after about 20 Minutes the log of the miele-gw stops with:
```
13:00:05.316 ERROR - Error while fetching token
java.lang.RuntimeException: Error while fetching token
	at de.rnd7.miele.api.MieleAPI.updateToken(MieleAPI.java:117)
	at de.rnd7.miele.api.SSEClient.start(SSEClient.java:99)
	at de.rnd7.mieletomqtt.Main.<init>(Main.java:51)
	at de.rnd7.mieletomqtt.Main.main(Main.java:72)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to api.mcs3.miele.com:443 [api.mcs3.miele.com/137.117.150.39] failed: Operation timed out (Connection timed out)
```

But don't starts over even when the internet was online again.

Perhaps it's because of the [shutdown](https://github.com/philipparndt/miele-to-mqtt-gw/blob/cef2cc341e03b531b6483119afc5486e2928bdc9/src/de.rnd7.mieletomqtt/src/main/java/de/rnd7/mieletomqtt/Main.java#L59) of the executor in the Main-Class?

Is there a other way to do this? I only get notice of it by accident.

Thanks, Alex

**Comment by philipparndt** [comment]
Hi Alex,

yes, we should implement two ways for the recovery:
1) When the application terminates, it is up to the user to set-up the docker container to restart on failure.
I think the application does not shut down correctly in all cases at the moment.

2) Improve handling connection lost within the app.

I try to come back to this next weekend ;)
