### ISSUE TITLE
since today the Client ist in a reconnecting loop: ERROR - JSONObject["value_raw"] is not a int.

### ISSUE THREAD

**Issue by AleksCee** [philipparndt/miele-to-mqtt-gw#62]
15:33:21.140 ERROR - JSONObject["value_raw"] is not a int.
org.json.JSONException: JSONObject["value_raw"] is not a int.
	at org.json.JSONObject.getInt(JSONObject.java:751)
	at de.rnd7.miele.api.MieleDevice.<init>(MieleDevice.java:25)
	at de.rnd7.miele.api.SSEClientHandler.lambda$handleDevices$0(SSEClientHandler.java:68)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at de.rnd7.miele.api.SSEClientHandler.handleEvent(SSEClientHandler.java:57)
	at de.rnd7.miele.api.SSEClientHandler.run(SSEClientHandler.java:37)
	at de.rnd7.miele.api.SSEClient.start(SSEClient.java:64)
	at de.rnd7.mieletomqtt.Main.<init>(Main.java:66)
	at de.rnd7.mieletomqtt.Main.main(Main.java:103)
Caused by: java.lang.NumberFormatException: For input string: "null"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.json.JSONObject.getInt(JSONObject.java:749)
	... 16 common frames omitted
15:33:21.142 INFO  - Wait for the network connection to come back (retry 1/10)

**Comment by AleksCee** [comment]
Seams to be a temporary problem - 1 hour later it's working again.
